# Generated by Django 4.1.6 on 2023-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
